Add two first recommendations for playbooks
redhat-cop/automation-good-practices pull request #19
Opened 2021-06-13 17:19 UTC by ericzolf

- Keep your playbooks as simple as possible
- Use tags cautiously either for roles or for complete purposes

2021-06-16 16:22 UTC, jscar-hawk reviewed
Eric, we need to check what ansible lint says about this before approving.

2021-06-30 17:01 UTC, mophahr requested changes
I have a few comments. they are all non-blocking but I didn't approve this PR, yet, so that it isn't merged before you had a chance to have a look :)

2021-06-30 17:17 UTC, mophahr commented
> Eric, we need to check what ansible lint says about this before approving.

@ericzolf @jscar-hawk, I have ansible-linted this playbook:

```
---
- name: ansible lint test playbook
  hosts: all
  gather_facts: false
  become: false
 
  tasks:

    - name: a task
      debug:
        msg: "that does nothing"
```

Ansible-lint doesn't complain – but I do :)

I still think there should be no empty line after list designators such as `tasks`, `roles`, `handlers` etc. 

My reasoning is that we don't do it with any other list. 
You would never do it with `tags:` or `when:`, for example.
So, by adding the empty line after `tasks`, `roles`, `handlers` etc. you obfuscate that a playbook is simply a _list_ of plays and that each play is a _dictionary_ containing _lists_ of `tasks`, `roles`, `handlers` and so on.
Understanding the latter helps tremendously with understanding what needs to be indented how far.

Just to be clear: I _do_ prefer to have an empty line _before_  `tasks`, `roles`, `handlers` … – just not after it.

2021-07-23 12:44 UTC, ericzolf commented on playbooks/README.adoc
> +TIP: the two list formats for tags are completely equivalent to each other in YAML.
Fair enough.

2021-07-23 12:44 UTC, ericzolf commented on playbooks/README.adoc
> +          tags: [role1, deploy]
Because it takes less space, but your are probably right :-)

2021-07-23 12:56 UTC, ericzolf commented on playbooks/README.adoc
> +Explanations:: either use tags called like the roles to switch on/off single roles, or to reach a complete meaningful suite of tasks, don't set tags which can't be used on their own.
I've created a list instead.

2021-07-23 12:57 UTC, ericzolf commented on playbooks/README.adoc
> +TIP: we'll explain later why there might be a case for using include_role/import_role tasks instead of the role section.
Yep.

2021-07-23 12:58 UTC, ericzolf commented
I'm not 100% convinced by the lack of empty line _after_ tasks, roles, etc... but I comply for now, we can still take a decision later and change it back.

2021-07-28 16:51 UTC, jscar-hawk commented
The Automation-CoP is delaying the decision on this one until our next meeting.

2021-08-11 13:38 UTC, mophahr approved these changes

2021-08-11 16:06 UTC, merged