Fix ansible_managed guideline to use comment filter
redhat-cop/automation-good-practices pull request #36
Opened 2022-01-13 12:42 UTC by spetrosi

The issue is that when a user has the `ansible_managed` variable set to a multi-line entry, `# {{ ansible_managed }}` in templates expands to the ansible_managed variable with only the first line commented out.
Ansible guidelines suggest replacing `# {{ ansible_managed }}` with `{{ ansible_managed | comment }}` so that all lines are commented out.
For more info, see e.g. https://bugzilla.redhat.com/show_bug.cgi?id=2006230

2022-01-13 12:49 UTC, ericzolf requested changes
IMHO the URL was wrong and I would add the explanation you put in the PR comment. Else, good one, thanks!
Note that we approve and merge PRs during the bi-weekly CoP meeting, next one on the 26th of January.

2022-01-13 12:49 UTC, ericzolf commented on roles/README.adoc
> +* Add ``{{ ansible_managed | comment }}`` at the top of the template file file to indicate that the file is managed by Ansible roles. For more information, see https://docs.ansible.com/ansible/latest
```suggestion
* Add ``{{ ansible_managed | comment }}`` at the top of the template file file to indicate that the file is managed by Ansible roles, while making sure that multi-line values are properly commented.
For more information, see https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#adding-comments-to-files[Adding comments to files].
```

2022-01-13 13:51 UTC, spetrosi commented
> IMHO the URL was wrong and I would add the explanation you put in the PR comment. Else, good one, thanks! Note that we approve and merge PRs during the bi-weekly CoP meeting, next one on the 26th of January.

Thank you, I've committed your change. We faced this issue in linux-system-roles, many config file break when ansible_managed variable was multi-line. Looking forward for the merge.

2022-01-26 10:27 UTC, ericzolf approved these changes

2022-01-26 17:21 UTC, mophahr commented
merged during the CoP meeting

2022-01-26 17:21 UTC, merged