Added debug verbosity
redhat-cop/automation-good-practices pull request #47
Opened 2022-03-09 19:17 UTC by bontreger

5th point in this blog from Tim Appnel https://www.ansible.com/blog/ansible-best-practices-essentials

2022-03-10 09:27 UTC, ericzolf requested changes
Looks mostly good to me and valuable. Few trifles to fix though. Thanks!

2022-03-10 09:27 UTC, ericzolf commented on playbooks/README.adoc
> +   msg: "Don't make messages always display"
```suggestion
- name: don't make messages always display
  debug:
    msg: "This message will clutter your log in production"
```
The indentation was slightly off and we recommend to always have a name

2022-03-10 09:27 UTC, ericzolf commented on playbooks/README.adoc
> +Rationale:: Debug messages are useful during testing and development, and can be useful to retain as playbooks go into production, but can cause concerns as they are shared between teams.
I would rather say that it clutters your log with possibly a lot of needless information which might confuse users.

2022-03-10 09:27 UTC, ericzolf commented on playbooks/README.adoc
> +   verbosity: 2
```suggestion
- name: this message will only appear when verbosity is 2 or more
  debug:
    msg: "Some more debug information if needed"
    verbosity: 2
```

2022-05-03 11:04 UTC, ericzolf commented
I think, my one comment hasn't been addressed/answered.

2022-05-18 15:49 UTC, mophahr commented on playbooks/README.adoc
> +Rationale:: Debug messages are useful during testing and development, and can be useful to retain as playbooks go into production for future troubleshooting. However, log messages will clutter your o
```suggestion
Rationale::
Debug messages are useful during testing and development, and can be useful to retain as playbooks go into production for future troubleshooting.
However, log messages will clutter your output, which can confuse users with non-relevant information.
```

2022-05-30 04:44 UTC, ericzolf approved these changes

2022-06-02 14:59 UTC, tima commented
Love it. Please include.

2022-06-15 15:59 UTC, sean-m-sullivan approved these changes
I like it.

2022-06-15 16:06 UTC, mophahr commented
Approved in the CoP meeting.

2022-06-15 16:06 UTC, merged